apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: website
spec:
  template:
    spec:
      containers:
      - name: website
        image: ghcr.io/o-p-n/website@sha256:bb48ecdd87dddd25bed2100971dd915cedf44987122d24fa9379b4a0cd64630f
