version: "3.9"

services:
  server:
    image: docker.io/linuxwolf/website:latest
    deploy:
      labels:
        - "traefik.enable=true"
        - "traeif.docker.network=public"
        - "traefik.http.routers.website.rule=Host(`outer-planes.net`)"
        - "traefik.http.routers.website.tls=true"
        - "traefik.http.routers.website.tls.certresolver=letsencrypt"
        - "traefik.http.routers.website.tls.domains[0].main=outer-planes.net"
        - "traefik.http.routers.website.tls.domains[0].sans=*.outer-planes.net"
        - "traefik.http.services.website.loadbalancer.server.port=80"
      restart_policy:
        condition: any
    networks:
      - public

networks:
  public:
    external: true
