version: "3.9"

services:
  server:
    image: ${DOCKER_REGISTRY:-localhost:5000}/o-p-n/website:${IMAGE_TAG:-latest}
    deploy:
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traeif.docker.network=public"
        - "traefik.http.routers.website.rule=Host(`outer-planes.net`)"
        - "traefik.http.routers.website.tls=true"
        - "traefik.http.routers.website.tls.certresolver=letsencrypt"
        - "traefik.http.routers.website.tls.domains[0].main=outer-planes.net"
        - "traefik.http.routers.website.tls.domains[0].sans=*.outer-planes.net"
        - "traefik.http.services.website.loadbalancer.server.port=4000"
      update_config:
        delay: 5s
        order: start-first
      restart_policy:
        condition: any
    networks:
      - public

networks:
  public:
    external: true
