version: "3"

includes:
  docker:
    taskfile: ./.builder/docker/taskfile.yaml
    internal: true

vars:
  DOCKER_CONTEXT: '{{ default "default" .DOCKER_CONTEXT }}'
  DOCKER_METADATA: '{{ default "target/metadata.json" .DOCKER_METADATA }}'

  DEFAULT_EPOCH: 0

  IMAGE_REPOSITORY: o-p-n/website
  IMAGE_TAG: '{{ coalesce .IMAGE_TAG "latest" }}'
  SOURCE_EPOCH: '{{ coalesce .SOURCE_EPOCH .DEFAULT_EPOCH }}'
  SOURCE_DATE:
    sh: date -u -d @{{ .SOURCE_EPOCH }} +"%Y-%m-%dT%H:%M:%S" 2> /dev/null || date -u -r {{ .SOURCE_EPOCH }} +"%Y-%m-%dT%H:%M:%S"

tasks:
  build:
    vars:
      SOURCE_DATE: '{{ .SOURCE_DATE }}'
    sources:
      - src/**
      - _config.ts
      - deno.json
      - deno.lock
    generates:
      - _site/**
    cmds:
      - deno task build
      - find _site | xargs -I{} touch -c -d "{{ .SOURCE_DATE }}Z" {}

  image:
    vars:
      SOURCE_EPOCH: '{{ .SOURCE_EPOCH }}'
    deps:
      - build
    cmds:
      - task: docker:image
        vars:
          IMAGE_REPOSITORY: o-p-n/website
          DOCKER_SOURCE_EPOCH: '{{ .SOURCE_EPOCH }}'
          IMAGE_TAG: '{{ .IMAGE_TAG }}'

  kustomize.env:
    vars:
      ENV: '{{ .ENV }}'
      K8S_REGISTRY: '{{.K8S_REGISTRY}}'
      IMAGE_DIGEST:
        sh: cat {{ .DOCKER_METADATA }} | jq -r '."containerimage.digest"'
      IMAGE: '{{ .K8S_REGISTRY }}/{{ .IMAGE_REPOSITORY }}@{{ .IMAGE_DIGEST }}'
    sources:
      - '{{ .DOCKER_METADATA }}'
    generates:
      - k8s/env/{{ .ENV }}/deployment-image-patch.yaml
    cmds:
      - |
        cat << ---EOF--- > k8s/env/{{ .ENV }}/deployment-image-patch.yaml
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: website
          namespace: website
        spec:
          template:
            spec:
              containers:
              - name: website
                image: {{ .IMAGE }}
        ---EOF---
  kustomize.only:
    vars:
      K8S_REGISTRY: '{{ coalesce .K8S_REGISTRY .DOCKER_REGISTRY }}'
    deps:
      - task: kustomize.env
        vars:
          ENV: intranet
          K8S_REGISTRY: '{{ .K8S_REGISTRY }}'
      - task: kustomize.env
        vars:
          ENV: public
          K8S_REGISTRY: '{{ .K8S_REGISTRY }}'

  kustomize:
    deps:
      - image
    cmds:
      - task: kustomize.only

  deploy.only:
    env:
      ENV: '{{.ENV}}'
    cmds:
      - o-p-n.deployer apply --env {{.ENV}}

  deploy.local:
    vars:
      ENV: local
      K8S_REGISTRY: host.minikube.internal:5000
      DOCKER_REGISTRY: localhost:5000
    cmds:
      - task: image
        vars:
          ENV: '{{ .ENV }}'
          DOCKER_REGISTRY: '{{ .DOCKER_REGISTRY }}'
      - task: deploy.only
        vars:
          ENV: '{{ .ENV }}'
