apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: website
spec:
  template:
    spec:
      containers:
      - name: website
        image: localhost:5000/o-p-n/website@sha256:5af37a8215974cd2183595d6390d2ac83c9e352abcb01b31255d709f4ec07c39
