name: deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "k8s/**"

jobs:
  publish-image:
    name: Deploy image
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - environment: intranet
            hostname: outer-planes.casa
          - environment: public
            hostname: outer-planes.net
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Tooling
        # TODO: convert into an action
        run: .github/scripts/install-tooling.sh
        env:
          INSTALL_PATH: /usr/local/bin
          GH_TOKEN: ${{ github.token }}
      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOYMENT_SSH_KEY }}" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat << ---EOF--- > ~/.ssh/config
          Host *
            User ${{ secrets.DEPLOYMENT_SSH_USERNAME }}
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          ---EOF---
      - name: Prepare Kubectl
        run: |
          mkdir -p ~/.kube
          ssh ${{ matrix.hostname }} /snap/bin/microk8s config \
            | sed -e 's/server: https:\/\/.*:/server: https:\/\/${{ matrix.hostname }}:/' \
            > ~/.kube/config
      - name: Deploy ${{ matrix.environment }}
        run: |
          o-p-n.deployer apply --env ${{ matrix.environment }}
          exit 0