name: publish
on:
  push:
    branches:
      - main
    paths-ignore:
      - "k8s/**"

jobs:
  publish-image:
    name: Publish image
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - name: "Generate access token"
        id: gentoken
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.RELEASE_MANAGER_APP_ID }}
          private-key: ${{ secrets.RELEASE_MANAGER_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ steps.gentoken.outputs.token }}
      - name: Setup Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.39.2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: Signin to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Caching
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ runner.os }}
      - name: Build and publish image
        run: |
          task kustomize \
            DOCKER_CACHE=/tmp/.buildx-cache \
            DOCKER_REGISTRY=ghcr.io \
            IMAGE_TAG=${{ github.sha }}
      - name: Create and Approve deployment PR
        env:
          GH_TOKEN: ${{ steps.gentoken.outputs.token }}
          GIT_USER_NAME: o-p-n-release-manager[bot]
          GIT_USER_EMAIL: ${{ secrets.RELEASE_MANAGER_APP_ID }}+o-p-n-release-manager[bot]@noreply.users.github.com
          GIT_SHA: ${{ github.sha }}
        run: .github/scripts/patch-image.sh
